###
## CREATE USER

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "firstName": "joao",
    "lastName": "teste 2",
    "email": "joao2@gmail.com",
    "phone": "102030",
    "address": {
        "street": "123",
        "city": "New",
        "state": "N",
        "country": "U",
        "zipcode": "123"
        }

}

###
## GET ALL USERS

GET http://localhost:8080/api/users

###

## UPDATE USER
PUT http://localhost:8080/api/users/12
Content-Type: application/json

{
    "firstName": "jose",
    "lastName": "teste 3",
    "email": "jose3@gmail.com",
    "phone": "10203040",
    "role": "CUSTOMER",
    "address": {
      "street": "123",
      "city": "New",
      "state": "N",
      "country": "U",
      "zipcode": "123"
    }
  }
